### ISSUE TITLE
{环境配置}[待确认]增加antv图表组件库

### ISSUE THREAD

**Issue by cwhnk** [nkucs/teacher-frontend#135]
由于vchart图表库不支持直方图，所以关于某题目运行时间分布统计的图表无法按照需求文档进行实现，建议添加antv，使用G2基础图表类库中的直方图进行实现。
@cnarutox @Zhang-YZ @Bay1997 @lzy732298218 @jiandaobao

**Comment by cnarutox** [comment]
建议很好，完全可以接受
@Bay1997 👍
