### ISSUE TITLE
{技术}[已解决] 整合统计模块各组件至页面

### ISSUE THREAD

**Issue by cnarutox** [nkucs/teacher-frontend#139]
#60  #72 
鉴于各组都已基本完成前端界面，接下来需要各组需要根据需求整合自己负责的模块的组件

组长 | 负责模块 | 负责组件
----- | ---------- | ---------
@Zhang-YZ | 统计概览 | 圆饼图
@jiandaobao  | 多个题目分析 | 词云
@Bay1997 | 学生统计 | 柱状图
@lzy732298218  | 单个题目分析 | 时间折线图

为了便于各组之间相互沟通交互，请各位组长将自己组完成/待完成的组件make a list：
`[是否可作为组件引用] 组件名 路径/位置`

**Example**
#### 组长名
- [x] 单个题目的提交次数的时间折线图
xxx\xxx\xx\xx\xx.vue Line xx

- [ ] xxx

.....
请于今晚7时前尽早汇报各组组员**连接公共数据库**情况以及**组件整合情况**

**Comment by jiandaobao** [comment]
**蹇坤霖**
- [x] 标签词云
src\views\stat\StatCourseAnalysis.vue

**Comment by Aya99code** [comment]
#### 组件
- [x] 柱状图
四个柱状图组件使用均可以参考`teacher-frontend/src/views/stat/StatStudentData.vue`
<img width="732" alt="image" src="https://user-images.githubusercontent.com/24248320/58533810-0c62af80-821c-11e9-9736-1654cb804ea4.png">

**Comment by lzy732298218** [comment]
**梁哲源**
- [x] 时间折线图和测例标签通过统计图
src\views\stat\StatProblem.vue
@Bay1997 单个题目执行用时分布图建议改成直方图

**Comment by Zhang-YZ** [comment]
**张宇哲**
- [x] 圆饼图
src\views\stat\StatOverview.vue
![image](https://user-images.githubusercontent.com/33855178/58538762-679a9f00-8228-11e9-83ad-aae03d88761b.png)
使用可参考上图，并且修改文件中对应的data
- [x] 教师端查看课程统计入口页面
- [x] 教师端点击查看题目和查看学生入口页面

**Comment by cnarutox** [comment]
@haspolat 这是我们组的页面组件完成情况，相应的Issue还有之前的分工： #60    #72 
因为学长统计的页面虽然由 @Bay1997 组负责，但是有些组件还是由其他组提供，所以你可以按需直接向他们索取
