### ISSUE TITLE
{环境配置}[已解决] 完成小组的创建

### ISSUE THREAD

**Issue by cnarutox** [nkucs/teacher-frontend#49]
### 请统计模块各组组长访问[新建团队页面](https://github.com/orgs/nkucs/teams)以以下格式创建Team并将组员拉入Team：
@Bay1997 @jiandaobao @lzy732298218 @Zhang-YZ 

![image](https://user-images.githubusercontent.com/28710281/58111526-34eb1800-7c24-11e9-81d8-248c416779a6.png)

1. 请组长收到issue后在右边的`Assignees`列表中将该issue分配到自己
2. 最后一位Assignee请将该issue状态更新为`已确认`
3. 第一位完成issue的Assignee请将该issue状态更新为`处理中`
4. issus完成后请在下方`Leave a comment`
5. 最后一位完成issue的Assignee请将该issue状态状态更新为`已解决`，并在下方@所有Assignees，说明是要申请关闭issue
### Note

> - 顺便附上[Issue规范](https://github.com/nkucs/opep/blob/master/README.md)，请各位组长及时传达给自己的每个组员
> - 组长与组员都有权力与义务相互督促监督，可在下方通过@对方来达到提醒效果

**Comment by Zhang-YZ** [comment]
@cnarutox  Zhang-YZ组已经完成创建小组issue

**Comment by lzy732298218** [comment]
@cnarutox 梁哲源组已经完成创建小组issue

**Comment by Aya99code** [comment]
@cnarutox 鲍阿勇组已经完成创建小组issue

**Comment by jiandaobao** [comment]
@cnarutox  蹇坤霖组已经完成创建小组issue

**Comment by jiandaobao** [comment]
@cnarutox @Zhang-YZ @lzy732298218 @Bay1997   申请关闭issue
