### ISSUE TITLE
{环境配置}[已完成] 完成环境配置

### ISSUE THREAD

**Issue by cnarutox** [nkucs/teacher-frontend#50]
#### 请以以下格式在评论区记录小组完成情况
- [x] 组长
> - [ ] 组员1
>> 未完成原因1
> - [x] 组员2
> - [ ] 组员3
>> 未完成原因3
> - [x] 组员4
1. 组长收到issue后请在右侧`Assignees`列表中添加自己
2. 最后一位收到issue的组长请将该issue状态更新为`已确认`
3. 第一位完成issue的Assignee请将该issue状态更新为处理中
4. 最后一位完成issue的Assignee请将该issue状态状态更新为已解决，并在下方@所有Assignees，说明是要申请关闭该issue
#### Note
> - 建议环境配置有问题的成员直接按照[Issue规范](https://github.com/nkucs/opep/blob/master/README.md)发Issue
> - 组长与组员都有权力与义务相互督促监督，可在下方通过@对方来达到提醒效果

**Comment by jiandaobao** [comment]
- [x] 蹇坤霖
> - [x] 曹原溥
> - [x] 陈彬
> - [x] 马弋涵

**Comment by lzy732298218** [comment]
- [x] 梁哲源
> - [x] 刘昊
> - [x] 刘贺
> - [x] 曾靖宇

**Comment by Zhang-YZ** [comment]
- [x] 张宇哲
  > - [x] 张鑫豪
> - [x] 杜心宇
> - [x] 张博健

**Comment by cnarutox** [comment]
@Bay1997

**Comment by Aya99code** [comment]
- [x] 鲍阿勇
>- [x] 李冠融 
>- [x] 陈威淮
>- [x] 陈禹乔
