### ISSUE TITLE
{需求}[已解决] 整合统计模块内容&明确分工

### ISSUE THREAD

**Issue by cnarutox** [nkucs/teacher-frontend#60]
#### 请各位组长将自己负责模块的内容按照图表进行分类整合，一来加深对模块的理解，二来便于接下来剥离不同模块中内容相近部分到一起，格式大概如下(以学生统计为例)：
---
### 学生统计
> 时间折线图
- 题目数量：统计某学生在**某时间**内AC通过的**题目的数量**并将其作为Y轴，以时间为X轴绘图
- 提交次数：统计某学生在**某时间**内的题目提交数量，可细分为**总数、AC和非AC**
> 圆饼图
- 课程题目数量：统计某学生在**某时间**内完成的所属于**不同课程**的题目数量，圆饼图的分类依据为课程
> 词云（**注意：目前所有测例便签的统计均由词云改为列表，因为标签不多，词云意义不大**）
- ......
### 单个题目分析
> ......
### 多个题目分析
> ......
### ......

# Note
- **Issue状态流转请参考 #49 #50** 
- **整合的内容直接留在评论区**
- **请各位尽快完成方便每个组确切地知道自己做什么，以及其他组做什么**
## Appendix
> [信息统计中心设计文档](https://www.chenwx.com/2019/04/05/statistical-design/)
![image](https://user-images.githubusercontent.com/28710281/58248186-130da480-7d8e-11e9-9b5e-816e8d2fab70.png)

**Comment by jiandaobao** [comment]
### 多个题目分析（课程内题目综合分析）
> 时间折线图
- 提交次数：统计所有题目学生的提交**总次数**，**AC提交次数**， **非AC提交次数**
> 词云（列表）
- **题目标签**：AC提交和非AC提交所在题目标签
> 柱状图
- **测例标签**：通过和未通过的测例标签
> 普通列表
- 提交次数：列出每一个题目的**提交次数**、**AC提交次数**、**非AC提交次数**

**Comment by Aya99code** [comment]
### 学生统计
> 时间折线图
- 题目数量：以时间为X轴，X轴单位长度可选一日、一周……；统计**某一学生**在**某段时间**内**AC通过**的题目的数量并将其作为Y轴绘图
- 某一题提交数量：以时间为X轴，X轴单位长度可选一日、一周……；统计**某一学生**在**某段时间**内对某一题**所有提交、AC、非AC**的数量作为Y轴绘图
> 圆饼图
- 题目所属课程占比：统计**某一学生**的所有完成题目中各个题目**所属课程**的比例
> 柱状图
- 提交时间段：以时间为X轴，X轴单位长度固定为一天中不同时间段；可选**统计时间范围**为一日、一周……，统计**某一学生**在所选**时间范围**内一天不同时段的提交数量和AC数量
> 词云
- AC题目标签：统计**某一学生**所做的**所有AC**的**题目的标签**并以词云形式展示
- 非AC题目标签：统计**某一学生**所做的**所有非AC**的**题目的标签**并以词云形式展示
> 测例标签（列表）
- 未通过的测例：统计**某一学生**所做的未通过的**测例标签**按数量由高到低以列表形式展示
- 通过的测例：统计**某一学生**所做过的已通过的**测例标签**按数量由高到低以列表形式展示

**Comment by lzy732298218** [comment]
### 单个题目分析
>柱状图

- 执行用时：统计该题目的各个用时的学生人数的占比，以**用时Runtime**为X轴，以**学生人数占比**为Y轴

>时间折线图

- 提交次数：统计该题目学生的**提交总次数，AC提交次数， 非AC提交次数**，以时间为X轴，X轴长度可选日、周......，以次数为Y轴

>测例标签（列表）

- 未通过的测例：统计**所有学生**所做的该题目未通过的**测例标签**按数量由高到低以列表形式展示
- 通过的测例：统计**所有学生**所做过的该题目已通过的**测例标签**按数量由高到低以列表形式展示

**Comment by cnarutox** [comment]
@Zhang-YZ

**Comment by Zhang-YZ** [comment]
### 统计概览
> 油表图（二分的圆饼图） 
- ac统计：所有提交中的AC个数占比统计
> 圆饼图
- 人数占比：所有学生依据年级划分的人数占比统计
- 题目占比：所有题目依据所属课程划分的每门课程题目占比统计
> 柱状图
- 人数统计：开设课程的选课人数统计

**Comment by Zhang-YZ** [comment]
@cnarutox @jiandaobao @Bay1997 @lzy732298218 申请关闭issue

**Comment by cnarutox** [comment]
#72
