### ISSUE TITLE
{需求}[已完成] 统计模块分工

### ISSUE THREAD

**Issue by cnarutox** [nkucs/teacher-frontend#72]
#60 
- [x] 时间折线图

- 多个题目分析（课程内题目综合分析）
  - 提交次数：统计所有题目学生的提交**总次数**，**AC提交次数**， **非AC提交次数**
- 学生统计
  - 题目数量：以时间为X轴，X轴单位长度可选一日、一周……；统计**某一学生**在**某段时间**内**AC通过**的题目的数量并将其作为Y轴绘图
  - 某一题提交数量：以时间为X轴，X轴单位长度可选一日、一周……；统计**某一学生**在**某段时间**内对某一题**所有提交、AC、非AC**的数量作为Y轴绘图
- 单个题目分析
  - 提交次数：统计该题目学生的**提交总次数，AC提交次数， 非AC提交次数**，以时间为X轴，X轴长度可选日、周......，以次数为Y轴
- 考试提交情况

- [x] 柱状图

- 学生统计
  - 提交时间段：以时间为X轴，X轴单位长度固定为一天中不同时间段；可选**统计时间范围**为一日、一周……，统计**某一学生**在所选**时间范围**内一天不同时段的提交数量和AC数量
- 单个题目分析
  - 执行用时：统计该题目的各个用时的学生人数的占比，以**用时Runtime**为X轴，以**学生人数占比**为Y轴
- 统计概览
  - 人数统计：开设课程的选课人数统计

- [x] 圆饼图/油菜图

- 学生统计
  - 题目所属课程占比：统计**某一学生**的所有完成题目中各个题目**所属课程**的比例
- 统计概览
  - 人数占比：所有学生依据年级划分的人数占比统计
  - 题目占比：所有题目依据所属课程划分的每门课程题目占比统计
  - ac统计：所有提交中的AC个数占比统计

- [x] 词云

- 多个题目分析（课程内题目综合分析）
  - 题目标签：统计课程中**所选题目**所做的的**题目的标签**并以词云形式展示
  - **题目标签**：AC提交和非AC提交所在题目标签
- 学生统计
  - AC题目标签：统计**某一学生**所做的**所有AC**的**题目的标签**并以词云形式展示
  - 非AC题目标签：统计**某一学生**所做的**所有非AC**的**题目的标签**并以词云形式展示

> 漂亮的图表（因测例数据较少，所以自由度较高，以漂亮的图表的形式展现即可）

- 多个题目分析（课程内题目综合分析）
  - **测例标签**：通过和未通过的测例标签
  - 提交次数：列出每一个题目的**提交次数**、**AC提交次数**、**非AC提交次数**
- 学生统计
  - 未通过的测例：统计**某一学生**所做的未通过的**测例标签**按数量由高到低以列表形式展示
  - 通过的测例：统计**某一学生**所做过的已通过的**测例标签**按数量由高到低以列表形式展示
- 单个题目分析
  - 未通过的测例：统计**所有学生**所做的该题目未通过的**测例标签**按数量由高到低以列表形式展示
  - 通过的测例：统计**所有学生**所做过的该题目已通过的**测例标签**按数量由高到低以列表形式展示
- 考试题目的测例标签统计
  - 所有未通过的测例标签
  - 所有通过的测例标签词云

### Note
- 前四个图表自由选择，选定后勾选并且leave a comment
- 最后的`漂亮的图表`中的测例统计各自负责各自部分的， @Zhang-YZ 负考试部分
- 此次分工的实际任务量会影响下次的分工，所以如果感觉不平均不用担心
- 状态流转流程参照之前

**Comment by Zhang-YZ** [comment]
@Zhang-YZ 组选择圆饼图
@cnarutox 考试题目的测例标签统计应该可以直接调用其他组写好的函数吧，需要重写么

**Comment by Aya99code** [comment]
@Bay1997 组选择柱状图

**Comment by lzy732298218** [comment]
@lzy732298218 组选择时间折线图

**Comment by jiandaobao** [comment]
@jiandaobao  选择词云

**Comment by jiandaobao** [comment]
@cnarutox @Zhang-YZ @Bay1997 @lzy732298218  
请求关闭
