### ISSUE TITLE
{环境配置}[进行中] 完成前端环境配置

### ISSUE THREAD

**Issue by cnarutox** [nkucs/teacher-frontend#78]
#### 请以以下格式在评论区记录小组完成情况
- [x] 组长
> - [ ] 组员1
>> 未完成原因1
> - [x] 组员2
> - [ ] 组员3
>> 未完成原因3
> - [x] 组员4
1. 组长收到issue后请在右侧`Assignees`列表中添加自己
2. 最后一位收到issue的组长请将该issue状态更新为`已确认`
3. 第一位完成issue的Assignee请将该issue状态更新为处理中
4. 最后一位完成issue的Assignee请将该issue状态状态更新为已解决，并在下方@所有Assignees，说明是要申请关闭该issue
#### Note
> - 建议环境配置有问题的成员直接按照[Issue规范](https://github.com/nkucs/opep/blob/master/README.md)发Issue
> - 组长与组员都有权力与义务相互督促监督，可在下方通过@对方来达到提醒效果
> - 不论使用npm还是yarn，截至发这个Issue为止，前端页面是如下所示
![image](https://user-images.githubusercontent.com/28710281/58329852-242ae400-7e68-11e9-9b44-370efe2e20d0.png)
> - 侧边栏的子项和相应的路由先由各组自行决定
#### 请各位组长于5月24日24点前汇报组内成员完成情况，届时该Issue会被close！

**Comment by Aya99code** [comment]
- [x] 鲍阿勇
> - [x] 陈威淮
> - [x] 陈禹乔
> - [x] 李冠融

**Comment by cnarutox** [comment]
@Zhang-YZ @lzy732298218 @jiandaobao

**Comment by Zhang-YZ** [comment]
- [x] 张宇哲
> - [x] 杜心宇
> - [x] 张博健
> - [x] 张鑫豪

**Comment by lzy732298218** [comment]
- [x] 梁哲源
> - [x] 刘昊
> - [x] 刘贺
> - [x] 曾靖宇

**Comment by jiandaobao** [comment]
- [x] 蹇坤霖
> - [x] 曹原溥
> - [x] 陈彬
> - [x] 马弋涵
