### ISSUE TITLE
{开发-5.26}[统计中心][统计概览](张宇哲) 教师开设课程到统计详情的页面设计

### ISSUE THREAD

**Issue by Zhang-YZ** [nkucs/teacher-frontend#84]

**Comment by DoThingYo** [comment]
fuck.
I thought it was a professor's reply from America.
This is mid-night for China.
Why not sleep?
little silly bear


| |
杜心宇
|
|
13102250917@163.com
|
签名由网易邮箱大师定制
在2019年5月25日 02:19，Donald<notifications@github.com> 写道：

Assigned #84 to @DoThingYo.

**Comment by Zhang-YZ** [comment]
ref 失误，84错写成了85

**Comment by Zhang-YZ** [comment]
finished

**Comment by Zhang-YZ** [comment]
![11](https://user-images.githubusercontent.com/33855178/58385110-ccce7480-801d-11e9-8988-5a6f73b2bddb.jpg)

**Comment by Zhang-YZ** [comment]
![11](https://user-images.githubusercontent.com/33855178/58385128-08693e80-801e-11e9-918b-d32155564a3d.jpg)

附一张图片，加载可能有点问题
