### ISSUE TITLE
{开发-5.26}[统计中心][统计概览](张宇哲) 查看题目、查看学生统计详情入口页面设计

### ISSUE THREAD

**Issue by Zhang-YZ** [nkucs/teacher-frontend#85]

**Comment by DoThingYo** [comment]
![12](https://user-images.githubusercontent.com/34271219/58385183-11a6db00-801f-11e9-8f75-bee1ef5a57c3.jpg)
![13](https://user-images.githubusercontent.com/34271219/58385185-14a1cb80-801f-11e9-8b2b-aa3897c6fe09.jpg)
完成界面

**Comment by DoThingYo** [comment]
@Zhang-YZ
